#!/bin/bash
# A5L 备份健康检查脚本
# 检查备份状态并生成报告

WORKSPACE="/workspace/projects/workspace"
DATE=$(date +%Y-%m-%d)
REPORT_FILE="$WORKSPACE/reports/backup_health_$DATE.md"

echo "# A5L 备份健康检查报告" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "**检查日期**: $DATE" >> "$REPORT_FILE"
echo "**检查时间**: $(date '+%H:%M:%S')" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

echo "## 备份状态概览" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 检查Tier 1
if [ -f "$WORKSPACE/.backup/daily/core/SOUL.md.$DATE.bak" ]; then
    echo "- ✅ Tier 1 Core: SOUL.md backed up" >> "$REPORT_FILE"
else
    echo "- ❌ Tier 1 Core: SOUL.md NOT backed up" >> "$REPORT_FILE"
fi

# 检查Tier 2
if [ -f "$WORKSPACE/.backup/daily/kg/knowledge_graph.db.$DATE.bak" ]; then
    echo "- ✅ Tier 2 KG: Database backed up" >> "$REPORT_FILE"
else
    echo "- ❌ Tier 2 KG: Database NOT backed up" >> "$REPORT_FILE"
fi

# 统计备份大小
echo "" >> "$REPORT_FILE"
echo "## 备份存储统计" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "| 层级 | 大小 |" >> "$REPORT_FILE"
echo "|------|------|" >> "$REPORT_FILE"
TIER1_SIZE=$(du -sh "$WORKSPACE/.backup/daily/core" 2>/dev/null | cut -f1)
TIER2_SIZE=$(du -sh "$WORKSPACE/.backup/daily/kg" 2>/dev/null | cut -f1)
echo "| Tier 1 Core | $TIER1_SIZE |" >> "$REPORT_FILE"
echo "| Tier 2 KG | $TIER2_SIZE |" >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"
echo "## 完整性检查" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 验证完整性哈希
if [ -f "$WORKSPACE/.backup/daily/core/integrity.$DATE.sha256" ]; then
    cd "$WORKSPACE/.backup/daily/core"
    if sha256sum -c "integrity.$DATE.sha256" > /dev/null 2>&1; then
        echo "- ✅ Tier 1 integrity check PASSED" >> "$REPORT_FILE"
    else
        echo "- ❌ Tier 1 integrity check FAILED" >> "$REPORT_FILE"
    fi
else
    echo "- ⚠️ Tier 1 integrity file not found" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by A5L Backup Health Check*" >> "$REPORT_FILE"

echo "Health check report generated: $REPORT_FILE"
